- hosts: lamp
  become: yes
  tasks:
   - name: install rsyslog
     yum:
       name: rsyslog
       state: latest

   - name: enable and start rsyslog server
     service:
       name: rsyslog
       enabled: yes
       state: started
       
   - name: configure rsyslog
     lineinfile:
       path: /etc/rsyslog.conf
       line: '*.* @172.20.0.4:514'
       state: present
     notify:
       - restart rsyslogd

  handlers:
   - name: restart rsyslogd
     service:
       name: rsyslog
       state: restarted
